### ISSUE TITLE
opinion requested: message bodies

### ISSUE THREAD

**Issue by ZhiLinR** [ZhiLinR/UBS-TTP#8]
currently my message bodies end with something simple like
``
res.status(500).send({ message: error.message });
``

would it be reccomended or good practise to make it more specific? say like the mongoDB error body where theres an error code and a normal errmsg both included?

``
 errorResponse: {
    index: 0,
    code: 11000,
    errmsg: 'E11000 duplicate key error collection: ttp_user.user index: user_id_text dup key: { _fts: "com", _ftsx: 0.6666666666666666 }',
    keyPattern: { _fts: 'text', _ftsx: 1 },
    keyValue: { _fts: 'com', _ftsx: 0.6666666666666666 }
  },
``

**Comment by cre8tion** [comment]
Feel free to add these comments under the pull request section instead of creating a new issue for it.

Responding to the question, you dont need to include an error code, it complicates things for you I feel.

A normal message like what you are doing is enough. But you can also consider to write a separate function to re use the { message: error.message}.

i.e.

function createErrorResponse(String errormessage) {
 return {
  message: errorMessage
 }
}

Feel free to add more details in the future if you need also

**Comment by cre8tion** [comment]
Feel free to close this issue if there are no further questions
